language: go
go:
- 1.13.x
cache:
  directories:
  - $GOPATH/pkg/mod
  - $HOME/.cache/go-build
env:
  global:
  - CGO_ENABLED=0
  - GO111MODULE=on
before_script:
- go mod download
script:
- make ci
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
